esphome:
  name: rower-esp32
  friendly_name: Rower ESP32

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
api:
  reboot_timeout: 0s
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source:
      type: git
      url: https://github.com/chruth/rower-esphome.git
      ref: main
    components: [rowing_monitor]

rowing_monitor:
  id: rm
  pin_step1: GPIO32
  pin_step2: GPIO33

  top_enter_threshold: -3
  top_leave_threshold: -5
  bottom_threshold: -10
  short_threshold: -8
  micro_threshold: -4
  min_stroke_ms: 700
  session_timeout_ms: 20000
  active_idle_ms: 1500
  meters_per_travel: 0.6667

  sensor:
    valid_strokes:
      name: "Rower Valid Strokes"
    short_strokes:
      name: "Rower Short Strokes"
    micro_strokes:
      name: "Rower Micro Strokes"
    spm:
      name: "Rower SPM"
    active_time:
      name: "Rower Active Time"
    distance:
      name: "Rower Distance"
    short_distance:
      name: "Rower Short Distance"
    micro_distance:
      name: "Rower Micro Distance"
    avg_valid_travel:
      name: "Rower Avg Valid Travel"
    avg_short_travel:
      name: "Rower Avg Short Travel"
    avg_micro_travel:
      name: "Rower Avg Micro Travel"

  text_sensor:
    phase:
      name: "Rower Phase"
