esphome:
  name: rower-esp32
  friendly_name: Rower ESP32

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
api:
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source:
      type: local
      path: my_components

joroto_rower:
  id: rower
  pin_step1:
    number: GPIO16
    mode:
      input: true
      pullup: true
  pin_step2:
    number: GPIO17
    mode:
      input: true
      pullup: true

  top_enter_threshold: -3
  top_leave_threshold: -5
  bottom_threshold: -10

  short_stroke_threshold: 8
  micro_stroke_threshold: 3

  min_stroke_ms: 700
  session_timeout_ms: 20000
  active_idle_ms: 600

  # Kalibrierung
  meters_per_valid_travel: 1.0
  meters_per_short_travel: 1.0
  meters_per_micro_travel: 1.0

  valid_strokes:
    name: "Valid Strokes"
  short_strokes:
    name: "Short Strokes"
  micro_strokes:
    name: "Micro Strokes"
  spm:
    name: "SPM"
  active_time:
    name: "Active Time"
  distance:
    name: "Distance"
  short_distance:
    name: "Short Distance"
  micro_distance:
    name: "Micro Distance"
  position:
    name: "Encoder Position"
